greeting:
  message: hello
  response: how are you
quarkus:
  http:
    cors:
      ~: true
      origins: http://localhost:4200
      methods: GET,PUT,POST,PATCH
      access-control-allow-credentials: true
  datasource:
    mongodb:
      connection-string: mongodb://localhost:27017/
      database: EMS